### PR TITLE
Fix for #80

### PR DESCRIPTION
**Pull request by SATOFish**
remove 'displayBuffer' from regex-railroad-diagram.coffee.
Fix for #80 
This will eliminate a Deprecated call.

### CODE REVIEW

**Comment by jediorange** [comment]
This is working for me, no more deprecated warnings.

**Comment by PeterTeng** [comment]
Working for me too👍

**Comment by pr-yemibedu** [comment]
Does this whole project deserve just being forked to carry forward the needed simple changes that are pending?

**Comment by mikesprague** [comment]
For anyone interested, I published a fork of this project with the necessary updates for Atom v1.13 and up. Not intending to develop it, just fix bugs like these. 

- https://github.com/mikesprague/atom-regex-railroad-diagrams-fork
- https://atom.io/packages/regex-railroad-diagram-fork

If development becomes active on this project again I'll gladly contribute back the updates and close mine.

**Comment by jediorange** [comment]
Thank you @mikesprague

**Comment by VNeddy** [comment]
This is working for me too, thank you

**Comment by klorenz** [comment]
Hi Mike,

thank you very much for this work.  I had no time last year to work on my 
projects and I this will continue for a while.  (I am building a house with
my family :) )

Would you like to be package maintainer?

I can give you access to the repo.

Best regards,

Kiwi

Am 20.02.2017 um 23:50 schrieb Mike Sprague:

**Comment by pr-yemibedu** [comment]
Hello,

  That would be helpful. Best of luck with the construction of your new 
home. Thank you. Good day.

**Comment by mikesprague** [comment]
@klorenz No thanks necessary! It was a minor fix for a minor annoyance. You did all the real work on this package.

I know how that goes (real life getting in the way, etc.). I'd be happy to be maintainer on the project, thanks for reaching out and asking.

Once you add me I'll submit a pull request with my changes and then merge them here. I'll also deprecate my fork and refer people back here.

Cheers!

Mike

**Comment by klorenz** [comment]
@mikesprague you are collaborator now :)

**Comment by mikesprague** [comment]
Thanks @klorenz! When I get home from work this evening I'll deprecate my fork and update this repo with the fix.

**Comment by mikesprague** [comment]
Closed by pull request #88 :fireworks: :tada:

**Pull request closed without merging**
