### PR TITLE
Rename styles directory

### LINKED ISSUE #37: Package.getStylesheetsPath is deprecated.
Since the update to Atom 0.189.0, this message appears:

Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `regex-railroad-diagram` package
```
Package.getStylesheetsPath (D:\Programme\Dokumente\Atom\resources\app\src\package.js:448:9)
Package.getStylesheetPaths (D:\Programme\Dokumente\Atom\resources\app\src\package.js:459:32)
```

The fix should be simple: You only have to rename the folder ```stylesheets``` to ```styles```. You also have to adjust the path if you used the original path in your code (I found one case in the file ```select-list-view.js``` at line 12).

### PR DESCRIPTION
**Pull request by goddamnhippie**
Closes #37

### CODE REVIEW

**Comment by jediorange** [comment]
Please accept. Seriously.

**Comment by petey** [comment]
Please accept this to get rid of depreciation warnings. Atom 1.0 will be released in June and this plugin will break without this change.

**Comment by brandonweiss** [comment]
@klorenz A merge would be awesome :)

**Comment by ilanbiala** [comment]
@klorenz what is taking so long to merge this PR? People use this package and if it is too hard to manage, can you add a collaborator?

**Comment by hairyhenderson** [comment]
+1 @klorenz please merge this - as of Atom 0.206.0 (released yesterday), deprecated APIs are gone, meaning **this plugin is _totally busted_**.

**Comment by brandonweiss** [comment]
Release, please?

**Pull request merged**
